import { getServerSession } from "next-auth"
import { Loginoptions } from "../api/auth/[...nextauth]/route"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  const session = getServerSession(Loginoptions)

  if (!session) {
    return redirect("/")
  }

  return (
    <html lang="en">
      <body className="poppins">
        {children}
      </body>
    </html>
  )
}
